### PR TITLE
Issue 72 add infraspecific nomenclature

### LINKED ISSUE #72: Infraspecific nomenclature
1. Sites using the chado 1.3 infraspecific nomenclature for organisms (e.g. subspecies) will have difficulty selecting the correct organism when adding a JBrowse instance as subspecies are currently not displayed. 
2. Organism list is in database order, it should be sorted

I will propose an appropriate fix for this.

### PR DESCRIPTION
**Pull request by dsenalik**
This implements infraspecific nomenclature and sorting of the organism list as described in issue #72

### CODE REVIEW

**Comment by laceysanderson** [comment]
Hi @dsenalik, I've fixed the testing in this repo (i.e. fixed the github action 🤩 ). Do you want to pull the most recent version of the 7.x-3.x branch in this module into your PR branch? That way we'll finally be able to see the testing! Thanks for your patience on this one!

**Comment by laceysanderson** [comment]
See this PR for an easy way to do that: https://github.com/dsenalik/tripal_jbrowse/pull/1

**Comment by dsenalik** [comment]
Thank you Lacey

**Review by laceysanderson — APPROVED** [review]
Thanks @dsenalik! The fix looks good and tests pass! 🎉 Thank you for the contribution <3

**Pull request merged**
