### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by jwest60**
#23 

I can't get the makefile to work on my machine, so I can't actually visually confirm that everything looks good. It would be helpful if it could be built through rtd on this branch, since I don't believe I can without admin privileges. Thanks in advance.

### CODE REVIEW

**Comment by laceysanderson** [comment]
Hi @jwest60, I tried to configure rtd to build this branch but it's not appearing under https://readthedocs.org/projects/tripal-jbrowse/versions/ so I can't enable it...

I tested this branch on my local and it builds for me
```
$ git clone https://github.com/tripal/tripal_jbrowse.git
$ cd tripal_jbrowse/docs
$ make html
Running Sphinx v1.8.1
making output directory...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                  
generating indices... genindex
writing additional pages... search
copying images... [100%] guide/../assets/instances.png                                                                                                          
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```
When I check the build, it has the following index:
Screen Shot 2019-06-11 at 2 44 05 PM

However, in order to integrate with the new module we're going to need to change this to make it clear it's for Tripal JBrowse Management. Maybe something like the following? What do you think @almasaeed2010?

- Installation (already exists)
    - Dependencies
    - Tripal JBrowse Management
        - Installation
        - Configuration
    - Tripal JBrowse Integration (existing)
- Tripal JBrowse Management
   - Managing Instances
   - Managing Tracks
- Tripal JBrowse Page Integration (existing)

**Comment by almasaeed2010** [comment]
The structure sounds good to me. Thanks @laceysanderson 

Please let me know if you need any help @jwest60

**Comment by jwest60** [comment]
@laceysanderson The documentation has been restructured to make it more clear that it's for jbrowse management.

**Comment by almasaeed2010** [comment]
This compiles for me and it functions properly. 

Any thoughts @laceysanderson?

Thanks @jwest60!

**Comment by laceysanderson** [comment]
Looks good to me :-) Thanks @jwest60!

**Pull request merged**
